# Generated by Django 4.2.4 on 2023-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprofile',
            name='loggedin_userid',
        ),
        migrations.RemoveField(
            model_name='editprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='editprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/default_user_image.jpg', null=True, upload_to='images/warehouse_owner/'),
        ),
    ]
