# Generated by Django 4.2.4 on 2023-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, default='images/default_user_image.jpg', null=True, upload_to='images/farmer/'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, default='images/default_warehouse_image.jpg', null=True, upload_to='images/warehouse/'),
        ),
        migrations.AddField(
            model_name='warehouse_owner',
            name='image',
            field=models.ImageField(blank=True, default='images/default_user_image.jpg', null=True, upload_to='images/warehouse_owner/'),
        ),
    ]
