# Generated by Django 4.2.5 on 2023-11-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_rename_bookings_booking_rename_units_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
