# Generated by Django 4.2.5 on 2023-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_farmer_user_alter_farmer_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='email',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
