# Generated by Django 4.2.4 on 2023-11-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_warehouse_owner_email_warehouse_owner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_owner',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
