# Generated by Django 4.2.4 on 2023-11-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_warehouse_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse_owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehouse_owner',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.warehouse_owner'),
            preserve_default=False,
        ),
    ]
