# Generated by Django 4.2.4 on 2023-11-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_warehouse_owner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.warehouse_owner'),
        ),
    ]
