# Generated by Django 4.2.4 on 2023-11-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_warehouse_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='unit',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.warehouse'),
            preserve_default=False,
        ),
    ]
